### ISSUE TITLE
Question: Does the bridge supports bidirectional MODBUS-MQTT exchange?

### ISSUE THREAD

**Issue by bcelary** [helioz2000/mbbridge#1]
Hi,
I am going through a number of projects on GH to find the right kind of MODBUS-MQTT bridge and looks like your project is exactly what I am after. I would like to hook up a number of input and output MODBUS RS485 boards that are cheaply available on Aliexpress to a RPi. But I need to convert between Modbus<--->MQTT to use Node-Red and Home Assistant easily with it.

Can I achieve both - setting MODBUS slave's state based on MQTT message and reading MODBUS slave's states and publishing to MQTT with your application? Based on the README it seems that it is doable.

Thanks!

**Comment by helioz2000** [comment]
yes - that's exactly what mbbridge is designed for and that's how I'm
using it.

**Comment by bcelary** [comment]
Perfect. Thank you!
